name: Create diary issue
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  create_diary_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Today's date
        run: echo "TODAY=$(date '+%Y-%m-%d(%a)')" >> $GITHUB_ENV
      - uses: imjohnbo/issue-bot@v3
        with:
          title: ${{ env.TODAY }}
          labels: Diary
